### ISSUE TITLE
/tebex sendlink - status code (400)

### ISSUE THREAD

**Issue by andrewkm** [tebexio/Tebex-Minecraft#13]
Paper 1.20.4 Build 389
Tebex-Minecraft v2.0.1 compiled against: https://github.com/tebexio/Tebex-Minecraft/commit/da5c972f8998341476f7f262f2eb5fd85a95ba7c

- `/tebex sendlink ERSReserve 2467036`
- https://i.imgur.com/794XItI.png

**Comment by WildBamaBoy** [comment]
It's looking like the command is functional, though there's a more descriptive error we can show. A few questions:
1. Does this happen for all players?
2. Has this particular player purchased before?
3. Does this player perhaps have a different name on their linked Microsoft account? Try that as the target username as well.
