### ISSUE TITLE
Cannot Connect to Tebex

### ISSUE THREAD

**Issue by AceSkym** [tebexio/Tebex-Minecraft#19]
Hello, I saw this error posted about a bungeecord server, but wasn't sure if I should add to that thread or create another because my server is of a different type. 

I use the Offline version of the store for Geyser compatibility. Everything was running fine until Friday, I found the error in your issue section but decided to post another since the issue is significant to my server running and my players and it hasn't been fixed yet. 

I run 1.20.4, Paper server through Apex Hosting with Geyser support and didn't have issues thrown in the console until Thursday/Friday. The error Posted below is on repeat in my console so long as the server is online. Any help is appreciated, thank you!

28.01 15:17:53 [Server] WARN [Tebex] Failed to get online commands: java.lang.NullPointerException: Cannot invoke "String.replaceFirst(String, String)" because "id" is null
28.01 15:17:53 [Server] WARN java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "String.replaceFirst(String, String)" because "id" is null
28.01 15:17:53 [Server] WARN at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
28.01 15:17:53 [Server] WARN at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
28.01 15:17:53 [Server] WARN at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
28.01 15:17:53 [Server] WARN at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
28.01 15:17:53 [Server] WARN at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
28.01 15:17:53 [Server] WARN at tebex-bukkit-2.0.0.jar//io.tebex.sdk.request.TebexRequest$1.onResponse(TebexRequest.java:120)
28.01 15:17:53 [Server] WARN at tebex-bukkit-2.0.0.jar//io.tebex.plugin.libs.okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
28.01 15:17:53 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
28.01 15:17:53 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
28.01 15:17:53 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:840)
28.01 15:17:53 [Server] WARN Caused by: java.lang.NullPointerException: Cannot invoke "String.replaceFirst(String, String)" because "id" is null
28.01 15:17:53 [Server] WARN at tebex-bukkit-2.0.0.jar//io.tebex.sdk.util.UUIDUtil.mojangIdToJavaId(UUIDUtil.java:14)
28.01 15:17:53 [Server] WARN at tebex-bukkit-2.0.0.jar//io.tebex.sdk.platform.Platform.lambda$handleOnlineCommands$4(Platform.java:193)
28.01 15:17:53 [Server] WARN at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
28.01 15:17:53 [Server] WARN ... 7 more

**Comment by WildBamaBoy** [comment]
Thanks for the report - this seems to be related to offline mode. Here's the main issue we're tracking for this problem: https://github.com/tebexio/Tebex-Minecraft/issues/17
