### ISSUE TITLE
Why couopns cannot be created in-game?

### ISSUE THREAD

**Issue by bobhenl** [tebexio/Tebex-Minecraft#20]
Hello, I was creating coupons for automatization, like for regular automatic weekly events or monthly leaderboards... Why was it removed, please? I believe it's useful.

**Comment by WildBamaBoy** [comment]
Coupon creation was largely unused in the previous plugin. The capability is included in the SDK here so that automation plugins can still be built, but a command to create coupons is not included with the official Tebex plugin.
