### ISSUE TITLE
Tebex plugin does not parse the {id} placeholder

### ISSUE THREAD

**Issue by fabianmakila** [tebexio/Tebex-Minecraft#22]
### Platform / version info
Platform: `Velocity 3.3.0-SNAPSHOT (git-59567512-b346)`
Tebex plugin version: `2.0.1`

### Issue description
I'm currently doing a proxy switch from Bungee to Velocity. At the same time I'm also switching from the old BuycraftX plugin to the new Tebex plugin.

Currently for some reason the `{id}` placeholder does not get parsed properly as seen in the debug below:
`[io.tebex.plugin.TebexPlugin]: Dispatching offline command 'lpv user {id} parent settrack vip vip-diamond' for player 'FabianAdrian2'`

The Luckperms command feedback also confirms the fact that the `{id}` placeholder did not get parsed properly:
`[LP] {id} is not a valid username/uuid.`

Looking at the payment in the webstore, we can see that the webstore itself parses the UUID correctly. So this is most likely a plugin issue.
![image](https://github.com/tebexio/Tebex-Minecraft/assets/44451855/e3d55652-9e9f-45be-8de8-8ef3d16e6b52)

**Comment by l3nnartt** [comment]
same issue here, the support told me end of the next week there will be a fix

**Comment by l3nnartt** [comment]
https://suggestions.tebex.io/337

**Comment by l3nnartt** [comment]
I updated the plugin but the problem still persists :x

**Comment by l3nnartt** [comment]
@WildBamaBoy can you say anything about that?
