### ISSUE TITLE
[Fabric] Versions 2.0.1 and 2.0.2 still have a hard dependency on 1.16.5, causing a crash on startup in Minecraft 1.20.1

### ISSUE THREAD

**Issue by techheadfred-git** [tebexio/Tebex-Minecraft#25]
Previous issue was closed in error.

With 2.0.1 installed:

[02:18:24] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Tebex' (tebex) 2.0.1 with any version that is compatible with:
		 - minecraft 1.20.1
More details:
	 - Mod 'Tebex' (tebex) 2.0.1 requires version 1.16.5 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.3.jar:?]

With 2.0.2 installed:

[02:24:00] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Tebex' (tebex) 2.0.2 with any version that is compatible with:
		 - minecraft 1.20.1
More details:
	 - Mod 'Tebex' (tebex) 2.0.2 requires version 1.16.5 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.3.jar:?]

**Comment by Panzerbyte** [comment]
I too would like support for newer Minecraft versions.

**Comment by imeesa** [comment]
@techheadfred-git @Panzerbyte I've opened pull #54 for this.

**Comment by WildBamaBoy** [comment]
We now have a pre-release version available that works with Minecraft/Fabric 1.20.4. I've included additional instructions if builds need to be made on other MC versions: https://github.com/tebexio/Tebex-Minecraft/releases/tag/v2.0.6-prerelease

**Comment by techheadfred-git** [comment]
> We now have a pre-release version available that works with Minecraft/Fabric 1.20.4. I've included additional instructions if builds need to be made on other MC versions: https://github.com/tebexio/Tebex-Minecraft/releases/tag/v2.0.6-prerelease

Many mods don't yet support 1.20.4, so thanks for this info.
I'll try building for 1.20.1
