### ISSUE TITLE
[Spigot/Minecraft Offline] Error On Commands being sent

### ISSUE THREAD

**Issue by usernamegithu210** [tebexio/Tebex-Minecraft#27]
## Please include the following information with your report
- Server type and version (ex. Spigot 1.18.2)
- Tebex plugin version (ex. 2.0.1)
- Description of the issue with any error messages, stack traces, or relevant logs.

Minecraft Offline/Geyser Server (Paper Spigot 1.20.4)
Tebex Plugin Version | Tebex 2.0.2

Whenever commands are being ran after someone purchases a package, the following errors are thrown to console, and nothing is executed.

`06.02 20:07:04 [Server] [WARN] [Tebex] Failed to perform check: java.lang.NullPointerException
06.02 20:07:04 [Server] [WARN] java.util.concurrent.CompletionException: java.lang.NullPointerException
06.02 20:07:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
06.02 20:07:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
06.02 20:07:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
06.02 20:07:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
06.02 20:07:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
06.02 20:07:04 [Server] [WARN] at tebex-bukkit-2.0.2.jar//io.tebex.sdk.request.TebexRequest$1.onResponse(TebexRequest.java:141)
06.02 20:07:04 [Server] [WARN] at tebex-bukkit-2.0.2.jar//io.tebex.plugin.libs.okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
06.02 20:07:04 [Server] [WARN] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
06.02 20:07:04 [Server] [WARN] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
06.02 20:07:04 [Server] [WARN] at java.base/java.lang.Thread.run(Thread.java:833)
06.02 20:07:04 [Server] [WARN] Caused by: java.lang.NullPointerException
06.02 20:07:04 [Server] [WARN] at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
06.02 20:07:04 [Server] [WARN] at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
06.02 20:07:04 [Server] [WARN] at tebex-bukkit-2.0.2.jar//io.tebex.sdk.platform.Platform.handleOnlineCommands(Platform.java:189)
06.02 20:07:04 [Server] [WARN] at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
06.02 20:07:04 [Server] [WARN] at tebex-bukkit-2.0.2.jar//io.tebex.sdk.platform.Platform.lambda$performCheck$2(Platform.java:154)
06.02 20:07:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
06.02 20:07:04 [Server] [WARN] ... 7 more
06.02 20:08:04 [Server] [WARN] [Tebex] Failed to perform check: java.lang.NullPointerException
06.02 20:08:04 [Server] [WARN] java.util.concurrent.CompletionException: java.lang.NullPointerException
06.02 20:08:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
06.02 20:08:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
06.02 20:08:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
06.02 20:08:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
06.02 20:08:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
06.02 20:08:04 [Server] [WARN] at tebex-bukkit-2.0.2.jar//io.tebex.sdk.request.TebexRequest$1.onResponse(TebexRequest.java:141)
06.02 20:08:04 [Server] [WARN] at tebex-bukkit-2.0.2.jar//io.tebex.plugin.libs.okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
06.02 20:08:04 [Server] [WARN] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
06.02 20:08:04 [Server] [WARN] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
06.02 20:08:04 [Server] [WARN] at java.base/java.lang.Thread.run(Thread.java:833)
06.02 20:08:04 [Server] [WARN] Caused by: java.lang.NullPointerException
06.02 20:08:04 [Server] [WARN] at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
06.02 20:08:04 [Server] [WARN] at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
06.02 20:08:04 [Server] [WARN] at tebex-bukkit-2.0.2.jar//io.tebex.sdk.platform.Platform.handleOnlineCommands(Platform.java:189)
06.02 20:08:04 [Server] [WARN] at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
06.02 20:08:04 [Server] [WARN] at tebex-bukkit-2.0.2.jar//io.tebex.sdk.platform.Platform.lambda$performCheck$2(Platform.java:154)
06.02 20:08:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
06.02 20:08:04 [Server] [WARN] ... 7 more
06.02 20:09:04 [Server] [WARN] [Tebex] Failed to perform check: java.lang.NullPointerException
06.02 20:09:04 [Server] [WARN] java.util.concurrent.CompletionException: java.lang.NullPointerException
06.02 20:09:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
06.02 20:09:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
06.02 20:09:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
06.02 20:09:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
06.02 20:09:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
06.02 20:09:04 [Server] [WARN] at tebex-bukkit-2.0.2.jar//io.tebex.sdk.request.TebexRequest$1.onResponse(TebexRequest.java:141)
06.02 20:09:04 [Server] [WARN] at tebex-bukkit-2.0.2.jar//io.tebex.plugin.libs.okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
06.02 20:09:04 [Server] [WARN] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
06.02 20:09:04 [Server] [WARN] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
06.02 20:09:04 [Server] [WARN] at java.base/java.lang.Thread.run(Thread.java:833)
06.02 20:09:04 [Server] [WARN] Caused by: java.lang.NullPointerException
06.02 20:09:04 [Server] [WARN] at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
06.02 20:09:04 [Server] [WARN] at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
06.02 20:09:04 [Server] [WARN] at tebex-bukkit-2.0.2.jar//io.tebex.sdk.platform.Platform.handleOnlineCommands(Platform.java:189)
06.02 20:09:04 [Server] [WARN] at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
06.02 20:09:04 [Server] [WARN] at tebex-bukkit-2.0.2.jar//io.tebex.sdk.platform.Platform.lambda$performCheck$2(Platform.java:154)
06.02 20:09:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
06.02 20:09:04 [Server] [WARN] ... 7 more
06.02 20:10:04 [Server] [WARN] [Tebex] Failed to perform check: java.lang.NullPointerException
06.02 20:10:04 [Server] [WARN] java.util.concurrent.CompletionException: java.lang.NullPointerException
06.02 20:10:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
06.02 20:10:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
06.02 20:10:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
06.02 20:10:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
06.02 20:10:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
06.02 20:10:04 [Server] [WARN] at tebex-bukkit-2.0.2.jar//io.tebex.sdk.request.TebexRequest$1.onResponse(TebexRequest.java:141)
06.02 20:10:04 [Server] [WARN] at tebex-bukkit-2.0.2.jar//io.tebex.plugin.libs.okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
06.02 20:10:04 [Server] [WARN] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
06.02 20:10:04 [Server] [WARN] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
06.02 20:10:04 [Server] [WARN] at java.base/java.lang.Thread.run(Thread.java:833)
06.02 20:10:04 [Server] [WARN] Caused by: java.lang.NullPointerException
06.02 20:10:04 [Server] [WARN] at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
06.02 20:10:04 [Server] [WARN] at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
06.02 20:10:04 [Server] [WARN] at tebex-bukkit-2.0.2.jar//io.tebex.sdk.platform.Platform.handleOnlineCommands(Platform.java:189)
06.02 20:10:04 [Server] [WARN] at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
06.02 20:10:04 [Server] [WARN] at tebex-bukkit-2.0.2.jar//io.tebex.sdk.platform.Platform.lambda$performCheck$2(Platform.java:154)
06.02 20:10:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
06.02 20:10:04 [Server] [WARN] ... 7 more
06.02 20:11:04 [Server] [WARN] [Tebex] Failed to perform check: java.lang.NullPointerException
06.02 20:11:04 [Server] [WARN] java.util.concurrent.CompletionException: java.lang.NullPointerException
06.02 20:11:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
06.02 20:11:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
06.02 20:11:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
06.02 20:11:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
06.02 20:11:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
06.02 20:11:04 [Server] [WARN] at tebex-bukkit-2.0.2.jar//io.tebex.sdk.request.TebexRequest$1.onResponse(TebexRequest.java:141)
06.02 20:11:04 [Server] [WARN] at tebex-bukkit-2.0.2.jar//io.tebex.plugin.libs.okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
06.02 20:11:04 [Server] [WARN] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
06.02 20:11:04 [Server] [WARN] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
06.02 20:11:04 [Server] [WARN] at java.base/java.lang.Thread.run(Thread.java:833)
06.02 20:11:04 [Server] [WARN] Caused by: java.lang.NullPointerException
06.02 20:11:04 [Server] [WARN] at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
06.02 20:11:04 [Server] [WARN] at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
06.02 20:11:04 [Server] [WARN] at tebex-bukkit-2.0.2.jar//io.tebex.sdk.platform.Platform.handleOnlineCommands(Platform.java:189)
06.02 20:11:04 [Server] [WARN] at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
06.02 20:11:04 [Server] [WARN] at tebex-bukkit-2.0.2.jar//io.tebex.sdk.platform.Platform.lambda$performCheck$2(Platform.java:154)
06.02 20:11:04 [Server] [WARN] at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
06.02 20:11:04 [Server] [WARN] ... 7 more`

**Comment by WildBamaBoy** [comment]
I think this was caused by f4179ba but I am not initially able to reproduce this.

Is your server running in online mode or offline mode?

Can you enable debug mode via the plugin as well, use `/tebex debug true` and paste your logs after the next command check runs. We should see [debug] log entries alongside errors similar to the ones you're showing here.

**Comment by usernamegithu210** [comment]
My java server is on "online" mode in the server.properties and requires everyone to have a fully paid for java account. However, I have geyser/online mode selected for my Tebex store as I use a plugin which allows offline players(aka Geyser/Floodgate/Bedrock MC players to join my java server. However, it isn't an interferance with the plugin, as I was still getting the error without Geyser installed.

I assume the error is because it's trying to run offline server commands onto an online server. However, I need to have it set as offline since geyser/bedrock players enter their xbox usernames.

here are my logs after resending commands from the store (aka buying a package)
https://privnote.com/1eWj7lqf#8bH8mG0Wf

^^ I used privnote to only allow one person to look at it, please make a copy if you need to refrence it.

**Comment by WildBamaBoy** [comment]
Try setting the plugin to proxy mode which will force it to use usernames instead of user IDs. In `plugins/Tebex/config.yml`, scroll to the bottom and you'll see:

```
# These settings are exclusive to this server.
# Do not share these credentials with anyone.
server:
  # Proxy Mode
  # If you are using BungeeCord/Velocity, set this to true.
  proxy: false
```

Change `proxy: false` to `proxy: true`, save, and restart. Let me know if the issue continues.

**Comment by usernamegithu210** [comment]
All works perfectly now! I suggest adding these steps on the tebex website to properly setup the plguin

**Comment by WildBamaBoy** [comment]
Thanks, glad it works! We will review our documentation as well to make sure it's up-to-date.
