### ISSUE TITLE
[Bukkit] /tebex sendlink <username> <packageId> won't send the link to the player

### ISSUE THREAD

**Issue by bobhenl** [tebexio/Tebex-Minecraft#28]
## Please include the following information with your report
- Server type and version (ex. Spigot 1.18.2) 1.20.1
- Tebex plugin version (ex. 2.0.1) 2.0.2
- Description of the issue with any error messages, stack traces, or relevant logs.
When using:
 /tebex sendlink <username> <packageId>

It doesn't send the link to the player, it sends to the people who executed the command. So, for example, in console, it sends the link to the console instead to the specified player.

**Comment by WildBamaBoy** [comment]
435b8ba
