### ISSUE TITLE
Webpanel images broken.

### ISSUE THREAD

**Issue by andrewkm** [tebexio/Tebex-Minecraft#3]
Webpanel player avatar images are broken.
Example: Payments page.

Tebex support was quite more efficient than overwolf and seeing as Jack from support told me to “remain patient as the dev team has been informed” however three days later simply auto closed my ticket because I didn’t respond I’ve decided to take my support request here.

“Our support team has been hard at work trying to address your concern, but unfortunately, we haven't heard back from you.

As we haven't received any updates regarding your pending ticket, we're considering the matter resolved.”

Broken images are not a resolved matter thus I’m curious if we are meant to respond every three days with words of encouragement or something of the sort?

**Comment by WildBamaBoy** [comment]
Hey there, issues for this repository are for the Minecraft plugin, not the Tebex web panel. Submitting a ticket is the appropriate action to take. 

I've gone ahead and forwarded this to our web dev team. Rest assured that it will be addressed as soon as possible.
