### ISSUE TITLE
Failed to check "string error" [Paper (Geyser) 1.20.4]

### ISSUE THREAD

**Issue by AceSkym** [tebexio/Tebex-Minecraft#39]
- Paper 1.20.4 running latest Geyser/Floodgate
- Tebex-bukkit-2.0.3
- Description of the issue with any error messages, stack traces, or relevant logs.

The console wasn't displaying any errors when updated and functioning as normal. However, when a user attempted to make a purchase this error began to throw in the console and repeats whenever the server is restarted. Additionally, the user did not receive their purchase/items/rank. The user was a Java user.

25.02 19:45:51 [Server] WARN [Tebex] Failed to perform check: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.UUID (java.lang.String and java.util.UUID are in module java.base of loader 'bootstrap')
25.02 19:45:51 [Server] WARN java.util.concurrent.CompletionException: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.UUID (java.lang.String and java.util.UUID are in module java.base of loader 'bootstrap')
25.02 19:45:51 [Server] WARN at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
25.02 19:45:51 [Server] WARN at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
25.02 19:45:51 [Server] WARN at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
25.02 19:45:51 [Server] WARN at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
25.02 19:45:51 [Server] WARN at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
25.02 19:45:51 [Server] WARN at tebex-bukkit-2.0.3.jar//io.tebex.sdk.request.TebexRequest$1.onResponse(TebexRequest.java:141)
25.02 19:45:51 [Server] WARN at tebex-bukkit-2.0.3.jar//io.tebex.plugin.libs.okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
25.02 19:45:51 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
25.02 19:45:51 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
25.02 19:45:51 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:840)
25.02 19:45:51 [Server] WARN Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.UUID (java.lang.String and java.util.UUID are in module java.base of loader 'bootstrap')
25.02 19:45:51 [Server] WARN at tebex-bukkit-2.0.3.jar//io.tebex.plugin.TebexPlugin.getPlayer(TebexPlugin.java:335)
25.02 19:45:51 [Server] WARN at tebex-bukkit-2.0.3.jar//io.tebex.plugin.TebexPlugin.isPlayerOnline(TebexPlugin.java:343)
25.02 19:45:51 [Server] WARN at tebex-bukkit-2.0.3.jar//io.tebex.sdk.platform.Platform.handleOnlineCommands(Platform.java:189)
25.02 19:45:51 [Server] WARN at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
25.02 19:45:51 [Server] WARN at tebex-bukkit-2.0.3.jar//io.tebex.sdk.platform.Platform.lambda$performCheck$2(Platform.java:156)
25.02 19:45:51 [Server] WARN at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
25.02 19:45:51 [Server] WARN ... 7 more
25.02 19:47:51 [Server] WARN [Tebex] Failed to perform check: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.UUID (java.lang.String and java.util.UUID are in module java.base of loader 'bootstrap')
25.02 19:47:51 [Server] WARN java.util.concurrent.CompletionException: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.UUID (java.lang.String and java.util.UUID are in module java.base of loader 'bootstrap')
25.02 19:47:51 [Server] WARN at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
25.02 19:47:51 [Server] WARN at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
25.02 19:47:51 [Server] WARN at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
25.02 19:47:51 [Server] WARN at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
25.02 19:47:51 [Server] WARN at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
25.02 19:47:51 [Server] WARN at tebex-bukkit-2.0.3.jar//io.tebex.sdk.request.TebexRequest$1.onResponse(TebexRequest.java:141)
25.02 19:47:51 [Server] WARN at tebex-bukkit-2.0.3.jar//io.tebex.plugin.libs.okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
25.02 19:47:51 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
25.02 19:47:51 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
25.02 19:47:51 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:840)
25.02 19:47:51 [Server] WARN Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.UUID (java.lang.String and java.util.UUID are in module java.base of loader 'bootstrap')
25.02 19:47:51 [Server] WARN at tebex-bukkit-2.0.3.jar//io.tebex.plugin.TebexPlugin.getPlayer(TebexPlugin.java:335)
25.02 19:47:51 [Server] WARN at tebex-bukkit-2.0.3.jar//io.tebex.plugin.TebexPlugin.isPlayerOnline(TebexPlugin.java:343)
25.02 19:47:51 [Server] WARN at tebex-bukkit-2.0.3.jar//io.tebex.sdk.platform.Platform.handleOnlineCommands(Platform.java:189)
25.02 19:47:51 [Server] WARN at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
25.02 19:47:51 [Server] WARN at tebex-bukkit-2.0.3.jar//io.tebex.sdk.platform.Platform.lambda$performCheck$2(Platform.java:156)
25.02 19:47:51 [Server] WARN at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
25.02 19:47:51 [Server] WARN ... 7 more

**Comment by WildBamaBoy** [comment]
This will be fixed in https://github.com/tebexio/Tebex-Minecraft/commit/52bace12f3c1d88945a07fcd544e469271d87f0c which will be included with a release this week.
