### ISSUE TITLE
[Question] Recent purchases (Was previously in the BuycraftX plugin)

### ISSUE THREAD

**Issue by Laukage** [tebexio/Tebex-Minecraft#42]
Hello,

There was previously a lot of features in the BuycraftX plugin, suddenly commands stop working with the old plugin so i had to switch to this new one...
I'm missing recent purchases specfically the head part... any eta for when this might come back?

![image](https://github.com/tebexio/Tebex-Minecraft/assets/46964809/f12e960e-5708-4534-a7ef-b8afefb80104)

- Paper 1.20.1
- Tebex 2.0.4

**Comment by WildBamaBoy** [comment]
The new plugin does not interact with signs. Buycraft Signs were replaced with the GUI store that players can open with `/buy` which was intended to be more intuitive than using the signs.

**Comment by Laukage** [comment]
> The new plugin does not interact with signs. Buycraft Signs were replaced with the GUI store that players can open with `/buy` which was intended to be more intuitive than using the signs.

I'm not talking about actually buying a rank, I'm talking about recent purchases?
Do you have a GUI that shows recent purchases or did you just remove the feature without any hesitation?
