### ISSUE TITLE
Hard Crash from Accessing LegacyRandomSource (Mixin) from multiple threads

### ISSUE THREAD

**Issue by JT122406** [tebexio/Tebex-Minecraft#47]
Fabric 0.15.7
Tebex 2.0.4
[crash-2024-03-18_21.11.30-server.txt](https://github.com/tebexio/Tebex-Minecraft/files/14750344/crash-2024-03-18_21.11.30-server.txt)

Seems to be based on Tebex doing things on async threads

**Comment by WildBamaBoy** [comment]
How often does this seem to occur? Is it random or does it happen after a certain event or after a certain time?

Also try enabling debug mode so we can see where exactly things are going wrong. Run `/tebex debug on` and then attempt the lookup. In your server logs, you'll see more in-depth information about requests and responses going to Tebex. Please copy/paste those relevant logs here and we can have a look.

**Comment by JT122406** [comment]
This occurs about 3-4 times a day on average on one of our servers.
It seems to be just random but it happens more when there are more purchases happening.
I will get debug info when I can

**Comment by WildBamaBoy** [comment]
Hi there @JT122406 just checking if you were able to collect any debug information?

**Comment by JT122406** [comment]
So far no because we changed our build to do everything on the main thread and that fixed the issue

**Comment by WildBamaBoy** [comment]
Do you mean this was a custom build of the Tebex plugin, or something else?

**Comment by JT122406** [comment]
We made a custom build to fix the issue
