### ISSUE TITLE
/tebex lookup

### ISSUE THREAD

**Issue by andrewkm** [tebexio/Tebex-Minecraft#50]
Paper 1.20.4 Build 463
Tebex-Minecraft v2.0.4 compiled against: https://github.com/tebexio/Tebex-Minecraft/commit/cb11989a783969256f40cf2671fee116065cc74d

`/tebex lookup <regular known player who has joined server>`
- Example: `/tebex lookup videowiz92`
- https://i.imgur.com/ypTcx3v.png

`/tebex lookup <player who hasn't joined your server and perhaps hasn't used tebex>`
- Example `/tebex lookup Johnson1`
- https://i.imgur.com/ZuaNtov.png

`/tebex lookup <player who is banned/chargedback on your server>`
- Example on ours: `/tebex lookup angelicdew`
- https://i.imgur.com/ZuaNtov.png

Lookup is completely broken.
Error's should be coherent and make sense.
Furthermore if a player hasn't joined one of your backend servers, there is no reason why this command shouldn't work as they are on your store via other servers.

Re-opening:
https://github.com/tebexio/Tebex-Minecraft/issues/12

**Comment by WildBamaBoy** [comment]
Can you enable debug mode and attempt to run the command again? We need to see the response from the API. Run `/tebex debug on` and then attempt the lookup. In your server logs, you'll see more in-depth information about the request and response. Please copy/paste those relevant logs here and we can have a look.

**Comment by WildBamaBoy** [comment]
Closing stale issue, be aware that /lookup requires a paid Tebex store plan
