### ISSUE TITLE
Cleanup network call log bombing...

### ISSUE THREAD

**Issue by andrewkm** [tebexio/Tebex-Minecraft#55]
Paper 1.20.4 Build 493
Tebex-Minecraft v.2.0.6 compiled against: https://github.com/tebexio/Tebex-Minecraft/commit/42194170e04ca76c5dc26028e8bd97bbc4162421

Catching this in console from time to time, very rarely, but it does happen.
https://pastebin.com/raw/0fb7tU97

May we please make this WARN a one liner.
This was one of the main reasons many of us forked BuyCraft and made changes ourselves, to remove this sort of console bombing from simple network calls to the Tebex API...

Better yet, can we just change it into a one liner at log level INFO...

**Comment by WildBamaBoy** [comment]
Apologies for the log spam. This is a timeout, which we do want reported to the user as a warning. We are aware of these timeouts occurring and are working on identifying the root cause, which seems to be related to the API infrastructure.
