### ISSUE TITLE
[Fabric] Server crash when player join

### ISSUE THREAD

**Issue by kirarcangell** [tebexio/Tebex-Minecraft#58]
- Server type: Fabric 0.15.11
- 
- Tebex fabric v2.0.2

--------------------------------------------------------------------------------------------------------------------------------------------
25.05 00:07:51 [Server] Server thread/INFO Sending server config values to client
25.05 00:07:52 [Server] Server thread/INFO Syncing config to kirarcangell (19c61ca4-fc3b-365c-abfa-3eb9b7d8efa3)
25.05 00:07:52 [Server] Server thread/ERROR Encountered an unexpected exception
25.05 00:07:52 [Server] INFO java.lang.NoSuchMethodError: 'java.lang.String net.minecraft.class_2561.method_10851()'
25.05 00:07:52 [Server] INFO at io.tebex.plugin.event.JoinListener.onPlayerJoin(JoinListener.java:21) ~[tebex-fabric-2.0.1.jar:?]
25.05 00:07:52 [Server] INFO at io.tebex.plugin.event.JoinListener.lambda$new$0(JoinListener.java:17) ~[tebex-fabric-2.0.1.jar:?]
25.05 00:07:52 [Server] INFO at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48) ~[fabric-networking-api-v1-1.3.11+1802ada577-cf20906c7ecece00.jar:?]
25.05 00:07:52 [Server] INFO at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:66) ~[fabric-networking-api-v1-1.3.11+1802ada577-cf20906c7ecece00.jar:?]
25.05 00:07:52 [Server] INFO at net.minecraft.class_3324.handler$clh000$fabric-networking-api-v1$handlePlayerConnection(class_3324.java:8518) ~[server-intermediary.jar:?]
25.05 00:07:52 [Server] INFO at net.minecraft.class_3324.method_14570(class_3324.java:215) ~[server-intermediary.jar:?]
25.05 00:07:52 [Server] INFO at net.minecraft.class_3248.method_33800(class_3248.java:131) ~[server-intermediary.jar:?]
25.05 00:07:52 [Server] INFO at net.minecraft.class_3248.method_14384(class_3248.java:118) ~[server-intermediary.jar:?]
25.05 00:07:52 [Server] INFO at net.minecraft.class_3248.redirect$cli000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:1063) ~[server-intermediary.jar:?]
25.05 00:07:52 [Server] INFO at net.minecraft.class_3248.method_18784(class_3248.java:68) ~[server-intermediary.jar:?]
25.05 00:07:52 [Server] INFO at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[server-intermediary.jar:?]
25.05 00:07:52 [Server] INFO at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
25.05 00:07:52 [Server] INFO at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
25.05 00:07:52 [Server] INFO at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
25.05 00:07:52 [Server] INFO at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
25.05 00:07:52 [Server] INFO at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
25.05 00:07:52 [Server] INFO at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
25.05 00:07:52 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
--------------------------------------------------------------------------------------------------------------------------------------------

**Comment by WildBamaBoy** [comment]
Hey there, looks like you're running an older version of the Fabric plugin (2.0.1). Please give the 2.0.6 prerelease a try here: https://github.com/tebexio/Tebex-Minecraft/releases/tag/v2.0.6-prerelease

The pre-release is only for Minecraft 1.20.4. If you're unable to use this version you can also use version 2.0.5 which is compatible with 1.16.5+: https://github.com/tebexio/Tebex-Minecraft/releases/tag/v2.0.5

**Comment by kirarcangell** [comment]
oh, i tested with both 2.0.2 and 2.0.1,

Still crashes with 2.0.5
-------------------------------------------------------------------------------------------------------------------------------
04.06 16:44:16 [Server] Server thread/ERROR Encountered an unexpected exception
04.06 16:44:16 [Server] INFO java.lang.NoSuchMethodError: 'java.lang.String net.minecraft.class_2561.method_10851()'
04.06 16:44:16 [Server] INFO at io.tebex.plugin.event.JoinListener.onPlayerJoin(JoinListener.java:21) ~[tebex-fabric-2.0.5.jar:?]
04.06 16:44:16 [Server] INFO at io.tebex.plugin.event.JoinListener.lambda$new$0(JoinListener.java:17) ~[tebex-fabric-2.0.5.jar:?]
04.06 16:44:16 [Server] INFO at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48) ~[fabric-networking-api-v1-1.3.11+1802ada577-cf20906c7ecece00.jar:?]
04.06 16:44:16 [Server] INFO at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:66) ~[fabric-networking-api-v1-1.3.11+1802ada577-cf20906c7ecece00.jar:?]
04.06 16:44:16 [Server] INFO at net.minecraft.class_3324.handler$cnd000$fabric-networking-api-v1$handlePlayerConnection(class_3324.java:8518) ~[server-intermediary.jar:?]
04.06 16:44:16 [Server] INFO at net.minecraft.class_3324.method_14570(class_3324.java:215) ~[server-intermediary.jar:?]
04.06 16:44:16 [Server] INFO at net.minecraft.class_3248.method_33800(class_3248.java:131) ~[server-intermediary.jar:?]
04.06 16:44:16 [Server] INFO at net.minecraft.class_3248.method_14384(class_3248.java:118) ~[server-intermediary.jar:?]
04.06 16:44:16 [Server] INFO at net.minecraft.class_3248.redirect$cne000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:1063) ~[server-intermediary.jar:?]
04.06 16:44:16 [Server] INFO at net.minecraft.class_3248.method_18784(class_3248.java:68) ~[server-intermediary.jar:?]
04.06 16:44:16 [Server] INFO at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[server-intermediary.jar:?]
04.06 16:44:16 [Server] INFO at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
04.06 16:44:16 [Server] INFO at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
04.06 16:44:16 [Server] INFO at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
04.06 16:44:16 [Server] INFO at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
04.06 16:44:16 [Server] INFO at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
04.06 16:44:16 [Server] INFO at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
04.06 16:44:16 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
04.06 16:44:16 [Server] Netty Server IO #4/INFO Receiving client config
----------------------------------------------------------------------------------------------------------------------------------
