### ISSUE TITLE
Tebex /reload doesn't reload buy command.

### ISSUE THREAD

**Issue by andrewkm** [tebexio/Tebex-Minecraft#61]
Tebex /reload doesn't reload buy command.
v2.0.6 compiled against https://github.com/tebexio/Tebex-Minecraft/commit/147172a392687454437648148eab093b7bff69e0
Paper 1.20.6 Build 148

Start server with buy command disabled.
Enable in config, save config, use /tebex reload in console.
Nothing.

**Comment by WildBamaBoy** [comment]
Please elaborate, are you saying that if you reload after enabling the /buy command, it remains disabled?

**Comment by andrewkm** [comment]
Correct.
