### ISSUE TITLE
[Velocity] Player queue executes no online commands

### ISSUE THREAD

**Issue by AoElite** [tebexio/Tebex-Minecraft#7]
Recently switched to this from BuycraftX. Have it configured and linked properly but it's not processing commands. Using latest version of Velocity, this plugin, and luckperms. Going to revert for now until resolved. Also noticed colored messages sent via the plugin aren't working on Velocity either.

**Comment by AoElite** [comment]
I think I know what the problem is. Since I run a multi proxy setup the commands issued by tebex are scheduled to run when the player is online when connected the proxy. However since some players aren't guaranteed to be load balanced to the proxy issuing the command it's sorta rng if the commands are ran or not. I don't see a configuration option to run commands even if they are offline but that might fix it.

**Comment by WildBamaBoy** [comment]
Are you able to tell us more about your setup? You say you have a multi-proxy setup, do you have Tebex installed on each server?

Online commands will execute as soon as the player connects to the proxy running Tebex.

Try running `/tebex forcecheck`, do your commands execute then?

**Comment by AoElite** [comment]
@WildBamaBoy I had tebex installed on each proxy, everything was setup properly. Since there's multiple proxies if a command is queued to run when the player is online when they connect to a specific proxy there's no guarantee that the player will be connected to the proxy that has the command queued.

**Comment by AoElite** [comment]
That's at least what I think is happening. Could just be that it doesn't work entirely on Velocity. I didn't have time to debug so I just switched back to BuycraftX.
